#pragma once

#ifndef BUTTON_MAPPINGS_DEFINED
#define BUTTON_MAPPINGS_DEFINED

#if defined(USE_MOMENTARY_MODE) && !defined(EVENT_MOMENTARY)
#define EVENT_MOMENTARY EV_5clicks
#endif

#if defined(EVENT_MOMENTARY) && !defined(EVENT_MOMENTARY_STROBE)
#define EVENT_MOMENTARY_STROBE EVENT_MOMENTARY
#endif

#if defined(USE_SUNSET_TIMER) && !defined(EVENT_HOLD_SUNSET_TIMER)
#define EVENT_HOLD_SUNSET_TIMER EV_click5_hold
#endif

#if !defined(NEXT_CHANNEL_MODE_EVENT)
#define NEXT_CHANNEL_MODE_EVENT EV_3clicks
#endif

#if defined(USE_RAMP_CONFIG) && !defined(EVENT_RAMP_CONFIG_HOLD)
#define EVENT_RAMP_CONFIG_HOLD EV_click7_hold
#endif

#ifndef LOCK_FROM_ON_EVENT
#define LOCK_FROM_ON_EVENT EV_4clicks
#endif

#ifndef TACTICAL_MODE_EVENT
#define TACTICAL_MODE_EVENT EV_6clicks
#endif

#ifndef EVENT_UNLOCK_TO_FLOOR
#define EVENT_UNLOCK_TO_FLOOR EV_click4_hold
#endif

#ifndef EVENT_UNLOCK_TO_CEILING
#define EVENT_UNLOCK_TO_CEILING EV_click5_hold
#endif

#ifndef EVENT_CHANNEL_CYCLE_LOCK_HOLD
#define EVENT_CHANNEL_CYCLE_LOCK_HOLD EV_click3_hold
#endif

#ifndef EVENT_SUNSET_TIMER_HOLD
#define EVENT_SUNSET_TIMER_HOLD EV_click12_hold
#endif

#ifndef EVENT_RAMP_STYLE_TOGGLE
#define EVENT_RAMP_STYLE_TOGGLE EV_6clicks
#endif

#define USE_POST_OFF_VOLTAGE_BRIGHTNESS_CONFIG
#define DEFAULT_POST_OFF_VOLTAGE_BRIGHTNESS_THRESHOLD (RAMP_SIZE/10)

//#ifndef MOMENTARY_TURBO_FROM_LOCK_EVENT
//  #define MOMENTARY_TURBO_FROM_LOCK_EVENT EV_click4_hold
//#endif

//#ifndef MOMENTARY_TURBO_FROM_LOCK_EVENT_RELEASE
//  #define MOMENTARY_TURBO_FROM_LOCK_EVENT_RELEASE EV_click4_hold_release
//#endif

//don't set events for new features here:
//PREV_CHANNEL_MODE_EVENT
//TURBO_1_EVENT
//TURBO_2_EVENT
//TURBO_3_EVENT
//MOMENTARY_TURBO_1_EVENT
//MOMENTARY_TURBO_1_RELEASE_EVENT
//MOMENTARY_TURBO_2_EVENT
//MOMENTARY_TURBO_2_RELEASE_EVENT
//MOMENTARY_TURBO_3_EVENT
//MOMENTARY_TURBO_3_RELEASE_EVENT
//TURBO_MAX_EVENT
//MOMENTARY_TURBO_MAX_EVENT
//MOMENTARY_TURBO_MAX_RELEASE_EVENT


//other stuff
//BLINK_LOCK_REMINDER
//USE_AUX_RGB_LEDS_WHILE_ON 50
//USE_AUX_RGB_LEDS_LOW_WHILE_ON 20
//USE_MANUAL_EEPROM_SAVE
//EVENT_MANUAL_EEPROM_SAVE
//BLINK_LOCK_REMINDER_CHANNEL
//BLINK_ONCE_USE_CONFIGURED_BLINK_CHANNEL
//USE_MOMENTARY_TURBO_FROM_LOCK
//TURBO_SHORTCUT_1_CHANNEL, EVENT_TURBO_SHORTCUT_1, EVENT_TURBO_SHORTCUT_1_MOMENTARY, EVENT_TURBO_SHORTCUT_1_MOMENTARY_RELEASE

//new ideas TODO:
// rampdown to off (https://old.reddit.com/r/flashlight/comments/13l3iwk/what_if_flashlights_gradually_rampd_off_when_you/jkpqxq5/)

// gave up on for now:
//POWERON_BLINK_CHANNEL
//LOCKOUT_EXIT_BLINK_CHANNEL
//AUX_CONFIG_BLINK_CHANNEL
//SIMPLE_UI_BLINK_CHANNEL
//MOMENTARY_BLINK_CHANNEL
//TACTICAL_BLINK_CHANNEL
//SAVE_MEMORY_BLINK_CHANNEL
//LOCK_BLINK_CHANNEL

#endif
